// TowersOfHanoi.cpp : Defines the entry point for the console application.
//
/*
The Tower of Hanoi is a mathematical game or puzzle. 
It consists of THREE rods and a number of disks of different sizes, which can slide onto any rod. 
The puzzle starts with the disks in a neat stack in ascending order of size on one rod, the smallest at the top, thus making a conical shape.

The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules:

1. Only one disk can be moved at a time.
2. Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack or on an empty rod.
3. No disk may be placed on top of a smaller disk.

Minimum number of moves is 2^n - 1 where n is the number of disks.

// Example:
This is for a 3 disk problem.
move disc 1 A to c ACB
move disc 2 A to b ABC
move disc 1 C to b CBA
move disc 3 A to c ACB
move disc 1 B to a BAC
move disc 2 B to c BCA
move disc 1 A to c ACB
Done in 7 moves.
*/

#include "stdafx.h"
#include <iostream>
#include <fstream>

using namespace std;


int moves(0);
void Hanoi(int m, char a, char b, char c);

void Hanoi(int m, char a, char b, char c) {
	moves++;
	if (m == 1) {
		cout << "Move disc " << m << " from " << a << " to " << c << endl;
	}
	else {
		Hanoi(m - 1, a, c, b);
		cout << "Move disc " << m << " from " << a << " to " << c << endl;
		Hanoi(m - 1, b, a, c);
	}
}

int main() {

	int discs;
	cout << "Enter the number of discs: " << endl;
	cin >> discs;
	Hanoi(discs, 'A', 'B', 'C');
	cout << "It took " << moves << " moves. " << endl;

	system("pause");

	/* For n = 10,
	Enter the number of discs:
	10
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 6 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 7 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 6 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 8 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 6 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 7 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 6 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 9 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 6 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 7 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 6 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 8 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 6 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 7 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 6 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 10 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 6 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 7 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 6 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 8 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 6 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 7 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 6 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 9 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 6 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 7 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 6 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 8 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 6 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 5 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 7 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 5 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 4 from C to B
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 6 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 4 from B to A
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 3 from C to A
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 5 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	Move disc 3 from A to B
	Move disc 1 from C to A
	Move disc 2 from C to B
	Move disc 1 from A to B
	Move disc 4 from A to C
	Move disc 1 from B to C
	Move disc 2 from B to A
	Move disc 1 from C to A
	Move disc 3 from B to C
	Move disc 1 from A to B
	Move disc 2 from A to C
	Move disc 1 from B to C
	It took 1023 moves.
	*/
}

